name: semi_logger
description: Color Logger and Base Exception for dart and flutter project.
version: 1.0.0+3
repository: https://github.com/sonnts996/semi_logger

environment:
  sdk: '>=2.12.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
