name: semi_exception
description: Default Dart Exception and Logger.
version: 1.0.0
repository: https://github.com/sonnts996/semi_exception

environment:
  sdk: '>=2.12.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
